before:
  hooks:
    - go mod download

builds:
  - id: "hcloud-pricing-exporter-cli"
    main: ./main.go
    binary: hcloud-pricing-exporter
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

archives:
  - name_template: "hcloud-pricing-exporter-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

source:
  enabled: true
  name_template: "hcloud-pricing-exporter-{{ .Version }}.src"

checksum:
  name_template: "hcloud-pricing-exporter-{{ .Version }}.checksums.txt"

milestones:
  - close: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
